"""
Prepzo AI Service - Internal AI Service
Fully Generative AI using Ollama - NO HARDCODED RESPONSES

This service provides conversational AI using only the local LLM.
All responses are DYNAMICALLY GENERATED by the AI model.
No templates, no hardcoded answers, no fallback messages.

IMPORTANT: If the model is unavailable, we return an error - NOT a fake response.
"""

from loguru import logger
from typing import List, Dict, Any, Optional
import re
import json


class InternalAIService:
    """
    Internal AI Service - 100% Generative
    
    Uses Ollama for all AI functionality.
    Every response is dynamically generated - no hardcoded templates.
    """
    
    def __init__(self):
        self._model_service = None  # Lazy loaded
    
    @property 
    def model_service(self):
        """Get the globally initialized model service from app.main"""
        if self._model_service is None:
            # Import the global instance that was initialized at startup
            from app.main import model_service as global_model_service
            self._model_service = global_model_service
        return self._model_service
    
    def _get_prepzo_system_prompt(self) -> str:
        """Get the default Prepzo AI system prompt"""
        return """You are the Prepzo AI Mentor. You aren't just an "AI assistant" - you are a high-level Mentor who helps students master tech and get hired.
        
        Your character:
        - Natural & Direct: Speak like a real technical mentor or senior dev. No fluff, no robotic formalisms.
        - Personalized: Always focus on the specific student's journey.
        - High-Fidelity: Provide code, career strategies, and deep technical answers exactly like a Senior Engineer.
        - Conversational: Keep it casual but professional. Never start with "As an AI..." or "I don't have access to...".
        
        Mandatory Format:
        - Direct output only. Never include subject lines, placeholders, or letter headers.
        - Use Markdown for structure and code.
        """
    
    def _build_contextualized_prompt(self, student_context: Dict[str, Any]) -> str:
        """Build a concise system prompt personalized for the student"""
        base_prompt = self._get_prepzo_system_prompt()
        
        # Keep context brief for smaller models
        name = student_context.get('name', 'Student')
        role = student_context.get('target_role', 'Software Engineer')
        weak = ', '.join(student_context.get('weak_areas', [])[:2]) or 'general skills'
        
        context_info = f"""

    Student detail for personalization:
    - Student Name: {name}
    - Aiming for: {role}
    - Key Gaps: {weak}

    Be a mentor to {name}. Help them with their specific goals."""
        
        return base_prompt + context_info

    def _clean_mentor_response(self, text: str) -> str:
        """Remove prompt-leakage and keep mentor output natural."""
        if not text or not isinstance(text, str):
            return ""

        lines = [line.rstrip() for line in text.splitlines()]

        # Filter lines that are clearly leaked instruction content.
        blocked_patterns = [
            r"format your response",
            r"important rules",
            r"never say",
            r"never repeat",
            r"end with exactly",
            r"specific websites",
            r"specific topics",
            r"do not output meta",
            r"student context",
            r"priority skill gaps",
            r"focus your advice on",
            r"respond naturally as the mentor",
            r"^subject:\s*",
            r"^dear\b",
            r"\[[^\]]+\]",
            r"sincerely",
            r"^student:\s*",
            r"^user:\s*",
            r"^assistant:\s*",
            r"^mentor:\s*",
            r"^me:\s*",
            r"^name:\s*",
            r"^target role:\s*",
            r"^priority skill",
            r"general skills gap",
            r"write like a real mentor",
            r"response style",
            r"start with a direct helpful answer",
            r"provide 3-5 practical next steps",
            r"follow-up question",
            r"guidelines",
        ]

        cleaned_lines = []
        for line in lines:
            lower = line.strip().lower()
            if not lower:
                cleaned_lines.append("")
                continue

            if any(re.search(pat, lower) for pat in blocked_patterns):
                continue

            # Remove accidental quoted policy/instruction fragments.
            if lower.startswith("-") and any(k in lower for k in ["never", "format", "important"]):
                continue

            cleaned_lines.append(line)

        cleaned = "\n".join(cleaned_lines).strip()

        # Collapse excessive blank lines.
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)

        # If the model produced an overly long checklist, keep it focused.
        numbered = re.findall(r"(?m)^\s*\d+[\.)]\s+", cleaned)
        if len(numbered) > 8:
            kept = []
            count = 0
            for line in cleaned.splitlines():
                if re.match(r"^\s*\d+[\.)]\s+", line):
                    count += 1
                    if count > 6:
                        continue
                kept.append(line)
            cleaned = "\n".join(kept).strip()

        return cleaned or text.strip()

    def _is_short_greeting(self, text: str) -> bool:
        """Detect simple greetings that should get brief conversational replies."""
        normalized = (text or "").strip().lower()
        if not normalized:
            return False
        greeting_inputs = {"hi", "hii", "hiii", "hello", "hey", "yo", "hiya", "sup"}
        return normalized in greeting_inputs

    def _is_small_talk(self, text: str) -> bool:
        """Detect casual small-talk queries that need brief chat replies."""
        normalized = (text or "").strip().lower()
        if not normalized:
            return False

        small_talk_phrases = [
            "how are you",
            "how r u",
            "how's it going",
            "whats up",
            "what's up",
            "you there",
            "how are things",
            "who are you",
            "what is your name",
            "what's your name",
            "your name",
        ]
        return any(p in normalized for p in small_talk_phrases)

    def _looks_formal_or_template(self, text: str) -> bool:
        """Detect letter-like/template responses that feel non-conversational."""
        if not text:
            return True

        lower = text.lower()
        patterns = [
            r"^subject:\s*",
            r"^dear\b",
            r"as a prepzo ai mentor",
            r"before we dive",
            r"sincerely",
            r"\[[^\]]+\]",
            r"\buser:\b",
            r"\bassistant:\b",
            r"\bstudent:\b",
        ]

        lines = [line.strip().lower() for line in text.splitlines() if line.strip()]
        first_line = lines[0] if lines else ""
        if any(re.search(p, first_line) for p in [r"^subject:\s*", r"^dear\b"]):
            return True

        return any(re.search(p, lower) for p in patterns)

    def _normalize_greeting_response(self, text: str) -> str:
        """Keep greeting responses short and chat-like."""
        cleaned = self._clean_mentor_response(text)
        if not cleaned:
            return ""

        lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
        if not lines:
            return cleaned

        # Prefer the first non-prefixed line.
        normalized_lines = []
        for line in lines:
            line = re.sub(r"^(ai\s*mentor\s*(\(.*?\))?\s*:\s*)", "", line, flags=re.IGNORECASE)
            line = re.sub(r"^(mentor\s*:\s*)", "", line, flags=re.IGNORECASE)
            line = re.sub(r"^([a-z\s]{0,20}mentor\s*:\s*)", "", line, flags=re.IGNORECASE)
            if line:
                normalized_lines.append(line)

        if not normalized_lines:
            return cleaned

        merged = " ".join(normalized_lines)
        merged = re.sub(r"\s+", " ", merged).strip()
        merged = merged.strip('"\'')

        # Keep max 2 sentences for greetings.
        sentences = re.split(r"(?<=[.!?])\s+", merged)
        return " ".join(sentences[:2]).strip()

    def _extract_json_reply(self, text: str) -> str:
        """Extract `reply` from a JSON model response when available."""
        if not text:
            return ""

        try:
            start = text.find("{")
            end = text.rfind("}") + 1
            if start == -1 or end <= start:
                return ""

            parsed = json.loads(text[start:end])
            reply = parsed.get("reply", "") if isinstance(parsed, dict) else ""
            return str(reply).strip()
        except Exception:
            return ""
    
    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        max_tokens: int = 1024,
        temperature: float = 0.7
    ) -> str:
        """
        Generate a response using the local LLM model
        
        This method uses ONLY the local LLM via Ollama.
        No external API calls. No hardcoded fallback responses.
        
        Raises:
            RuntimeError: If AI model is unavailable
        """
        # Build full prompt with conversation context
        full_prompt = prompt
        
        # For smaller models, keep history minimal and structured
        if conversation_history:
            # Only use last 2 exchanges (4 messages) for small models
            recent = conversation_history[-4:]
            history_text = "\n".join([
                f"{'User' if msg['role']=='user' else 'Mentor'}: {msg['content'][:200]}"
                for msg in recent
            ])
            full_prompt = (
                f"Conversation so far:\n{history_text}\n\n"
                f"User's latest message: {prompt}\n\n"
                "Respond naturally as the mentor. Do not output meta-instructions."
            )
        
        # Always use the model - no hardcoded fallbacks
        response = await self.model_service.generate(
            prompt=full_prompt,
            system_prompt=system_prompt or self._get_prepzo_system_prompt(),
            max_tokens=max_tokens,
            temperature=temperature
        )
        
        return response
    
    async def chat(
        self,
        message: str,
        student_context: Dict[str, Any],
        conversation_history: Optional[List[Dict[str, str]]] = None,
        temperature: float = 0.7,
        max_tokens: int = 800
    ) -> str:
        # Instant high-fidelity greeting to ensure personalization and avoid model drift
        if self._is_short_greeting(message) or self._is_small_talk(message):
            name = student_context.get('name', student_context.get('fullName', 'Student'))
            gaps = student_context.get('weak_areas', [])
            greeting_msg = f"Hey {name}! Good to see you. "
            if gaps:
                greeting_msg += f"Ready to dive back into {gaps[0]}, or should we work on your {student_context.get('target_role', 'Software Engineer')} strategies today?"
            else:
                greeting_msg += "What's on your mind? We can work on code, your resume, or some mock interview practice."
            return greeting_msg

        system_prompt = self._build_contextualized_prompt(student_context)
        messages: List[Dict[str, str]] = [{"role": "system", "content": system_prompt}]

        if conversation_history:
            # Keep recent context only to reduce drift on smaller models.
            for msg in conversation_history[-8:]:
                role = msg.get("role", "user")
                if role == "assistant":
                    role = "assistant"
                elif role == "system":
                    role = "system"
                else:
                    role = "user"

                content = (msg.get("content") or "").strip()
                if content:
                    messages.append({"role": role, "content": content[:500]})

        messages.append({"role": "user", "content": message})

        response = await self.model_service.chat(
            messages=messages,
            max_tokens=max_tokens,
            temperature=temperature
        )

        return self._clean_mentor_response(response)
    
    async def generate_interview_question(
        self,
        topic: str,
        difficulty: str = "medium",
        student_context: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generate a unique interview question using the AI model"""
        weak_areas = student_context.get('weak_areas', []) if student_context else []
        target_role = student_context.get('target_role', 'Software Engineer') if student_context else 'Software Engineer'
        skill_level = student_context.get('skill_level', 'Intermediate') if student_context else 'Intermediate'
        
        prompt = f"""Generate ONE unique, realistic interview question for a {target_role} position.

Context:
- Topic/Skill: {topic}
- Difficulty Level: {difficulty}
- Student Level: {skill_level}
- Areas to challenge: {', '.join(weak_areas[:3]) if weak_areas else 'General fundamentals'}

Requirements:
1. Create a question that top tech companies actually ask
2. Make it specific and practical, not vague
3. Include a brief hint about what you're looking for in the answer
4. For coding questions, include a clear example input/output

Format your response as:

📋 **Interview Question**
[Your specific question here]

📝 **Example** (if applicable)
[Input/Output example]

💡 **What I'm looking for:**
[2-3 key points you want to see in the answer]"""
        
        return await self.model_service.generate(
            prompt=prompt,
            system_prompt="You are a senior technical interviewer at a FAANG company. Generate realistic, challenging interview questions that test real understanding, not just memorization.",
            max_tokens=500,
            temperature=0.85  # Higher temperature for variety
        )
    
    async def evaluate_answer(
        self,
        question: str,
        answer: str,
        topic: str
    ) -> str:
        """Evaluate a student's interview answer using AI"""
        prompt = f"""Evaluate this interview answer as a senior technical interviewer.

QUESTION:
{question}

STUDENT'S ANSWER:
{answer}

TOPIC: {topic}

Provide a detailed, constructive evaluation:

1. **Score** (out of 10): Give a fair score with brief justification

2. **What You Did Well**: 
   - List specific strengths in the answer

3. **Areas for Improvement**:
   - List specific gaps or errors
   - Explain why these matter

4. **Better Answer**:
   - Show how to improve the answer
   - Include any missing key points

5. **Interview Tip**:
   - One actionable tip for similar questions

Be encouraging but honest. Help the student improve."""
        
        return await self.model_service.generate(
            prompt=prompt,
            system_prompt="You are a supportive but rigorous technical interviewer. Give honest, constructive feedback that helps students improve.",
            max_tokens=700,
            temperature=0.6
        )
    
    async def explain_concept(
        self,
        concept: str,
        student_level: str = "Intermediate",
        depth: str = "detailed"
    ) -> str:
        """Explain a technical concept with examples"""
        prompt = f"""Explain the concept: "{concept}"

Student Level: {student_level}
Explanation Depth: {depth}

Structure your explanation as follows:

🎯 **What is {concept}?**
[Simple definition in 1-2 sentences]

🌍 **Real-World Analogy**
[An everyday example that makes it click]

⚙️ **How It Works**
[Technical explanation appropriate for the student's level]

💻 **Code Example** (if applicable)
[Practical code snippet with comments]

❓ **Common Interview Questions**
[2-3 typical questions asked about this topic]

💡 **Key Points to Remember**
[3-4 bullet points for quick revision]

Make the explanation engaging and easy to understand."""
        
        return await self.model_service.generate(
            prompt=prompt,
            system_prompt="You are an expert teacher who makes complex concepts simple. Use analogies, examples, and clear structure.",
            max_tokens=1000,
            temperature=0.7
        )
    
    async def generate_study_plan(
        self,
        topics: List[str],
        duration_weeks: int,
        student_context: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generate a personalized study plan"""
        target_role = student_context.get('target_role', 'Software Engineer') if student_context else 'Software Engineer'
        skill_level = student_context.get('skill_level', 'Intermediate') if student_context else 'Intermediate'
        
        prompt = f"""Create a {duration_weeks}-week personalized study plan.

Student Profile:
- Target Role: {target_role}
- Current Level: {skill_level}
- Topics to Cover: {', '.join(topics)}

Create a detailed week-by-week plan that includes:

📅 **Week-by-Week Breakdown**
For each week:
- Main focus topic
- Daily goals (1-2 hours of study)
- Practice problems to solve
- Mini-project or hands-on task

📊 **Milestones**
- What they should achieve by each week

📚 **Resources**
- Specific courses, videos, or articles for each topic

🎯 **Daily Routine Suggestion**
- Morning/Afternoon/Evening breakdown

💪 **Motivation Tips**
- How to stay consistent

Make the plan realistic and achievable."""
        
        return await self.model_service.generate(
            prompt=prompt,
            system_prompt="You are a career coach who creates actionable, realistic study plans that students actually follow through.",
            max_tokens=1200,
            temperature=0.7
        )
    
    async def generate_project_idea(
        self,
        skills: List[str],
        difficulty: str = "intermediate",
        student_context: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generate a portfolio project idea"""
        target_role = student_context.get('target_role', 'Software Engineer') if student_context else 'Software Engineer'
        
        prompt = f"""Suggest ONE impactful portfolio project idea.

Requirements:
- Target Role: {target_role}
- Skills to Showcase: {', '.join(skills)}
- Difficulty: {difficulty}

Provide:

🚀 **Project Name**
[Creative, memorable name]

📝 **Description**
[What the project does - 2-3 sentences]

🎯 **Why This Project?**
[How it impresses recruiters for {target_role} roles]

🛠️ **Tech Stack**
[Specific technologies to use]

📋 **Core Features**
[5-7 features to implement]

📈 **Bonus Features**
[2-3 advanced features to stand out]

⏱️ **Timeline**
[Realistic timeline for completion]

💼 **Interview Talking Points**
[What to highlight when discussing this project]

Make the project unique, not a typical todo/weather app."""
        
        return await self.model_service.generate(
            prompt=prompt,
            system_prompt="You are a tech lead who has reviewed thousands of portfolios. Suggest projects that actually impress and differentiate candidates.",
            max_tokens=800,
            temperature=0.85
        )


# Singleton instance
_internal_ai_service: Optional[InternalAIService] = None


def get_internal_ai_service() -> InternalAIService:
    """Get or create the internal AI service singleton"""
    global _internal_ai_service
    if _internal_ai_service is None:
        _internal_ai_service = InternalAIService()
    return _internal_ai_service
