"""
Prepzo AI Service - LLM Model Service
Generative AI using Ollama (local LLM server) - NO external AI APIs
Supports: Mistral, LLaMA, Phi, Gemma, and other open-source models

IMPORTANT: All responses are dynamically generated by the AI model.
No hardcoded or template responses.
"""

import httpx
from loguru import logger
from typing import Optional, List, Dict, Any
import asyncio
import json

from app.config import get_settings


class ModelService:
    """
    Generative AI Service supporting multiple providers (Ollama, Groq, Gemini)
    
    Fully self-hosted or cloud-bridged - All responses are DYNAMICALLY GENERATED.
    """
    
    def __init__(self):
        self.settings = get_settings()
        self.provider = getattr(self.settings, 'ai_provider', 'ollama').lower()
        
        # Ollama settings
        self.ollama_base_url = getattr(self.settings, 'ollama_url', 'http://localhost:11434')
        self.ollama_model = getattr(self.settings, 'ollama_model', 'llama3.2:1b')
        
        # Groq settings
        self.groq_api_key = getattr(self.settings, 'groq_api_key', '')
        self.groq_model = getattr(self.settings, 'groq_model', 'llama-3.1-70b-versatile')
        
        self.model_name = self.groq_model if self.provider == 'groq' else self.ollama_model
        self._initialized = False
        self._available = False
        self.http_client: Optional[httpx.AsyncClient] = None
    
    async def initialize(self):
        """Initialize connection to AI provider"""
        if self._initialized:
            return
        
        self.http_client = httpx.AsyncClient(timeout=600.0)
        
        if self.provider == 'groq':
            if not self.groq_api_key:
                logger.warning("⚠️ Groq API key not configured")
                self._available = False
            else:
                # Basic check for Groq availability
                try:
                    # Just check if we can reach the API (we'll assume key is valid for now)
                    self._available = True
                    logger.info(f"✅ Groq Cloud connected - using model: {self.model_name}")
                except Exception as e:
                    logger.error(f"⚠️ Groq connection error: {e}")
                    self._available = False
        else:
            # Check if Ollama is running
            try:
                response = await self.http_client.get(f"{self.ollama_base_url}/api/tags")
                if response.status_code == 200:
                    models = response.json().get('models', [])
                    full_model_names = [m.get('name', '') for m in models if m.get('name')]
                    base_model_names = [name.split(':')[0] for name in full_model_names]

                    # Resolve configured model name to an exact installed tag.
                    resolved_model = None
                    if self.ollama_model in full_model_names:
                        resolved_model = self.ollama_model
                    elif f"{self.ollama_model}:latest" in full_model_names:
                        resolved_model = f"{self.ollama_model}:latest"
                    elif self.ollama_model in base_model_names:
                        for name in full_model_names:
                            if name.split(':')[0] == self.ollama_model:
                                resolved_model = name
                                break

                    if resolved_model:
                        self.model_name = resolved_model
                        self._available = True
                        logger.info(f"✅ Ollama connected - using model: {self.model_name}")
                    else:
                        logger.warning(f"⚠️ Model '{self.ollama_model}' not found in Ollama")
                        if models:
                            self.model_name = full_model_names[0]
                            self._available = True
                            logger.info(f"   Using available model: {self.model_name}")
                else:
                    logger.warning("⚠️ Ollama server responded but with unexpected status")
                    
            except httpx.ConnectError:
                logger.warning("⚠️ Ollama server not running at " + self.ollama_base_url)
            except Exception as e:
                logger.warning(f"⚠️ Could not connect to Ollama: {e}")
        
        self._initialized = True
    
    @property
    def has_model(self) -> bool:
        """Check if a model is available for inference"""
        return self._available
    
    def _clean_response(self, text: str) -> str:
        """Strip unnecessary markdown formatting if it wraps the whole response"""
        if not text:
            return text
        text = text.strip()
        # Remove surrounding quotes or double stars if they wrap the whole thing
        if text.startswith('**') and text.endswith('**'):
            text = text[2:-2].strip()
        if text.startswith('"') and text.endswith('"'):
            text = text[1:-1].strip()
        # Sometimes models add a leading "AI:" or "Mentor:"
        if text.lower().startswith("mentor:"):
            text = text[7:].strip()
        return text

    async def generate(
        self,
        prompt: str,
        max_tokens: Optional[int] = None,
        temperature: Optional[float] = None,
        top_p: Optional[float] = None,
        stop: Optional[List[str]] = None,
        system_prompt: Optional[str] = None
    ) -> str:
        """
        Generate text using selected AI provider - ALWAYS dynamic, never hardcoded
        """
        if not self._initialized:
            await self.initialize()

        if not self._available:
            raise RuntimeError(f"AI provider '{self.provider}' not available.")
        
        # Build messages for chat format
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        
        try:
            if self.provider == 'groq':
                # Groq API call (Cloud)
                headers = {
                    "Authorization": f"Bearer {self.groq_api_key}",
                    "Content-Type": "application/json"
                }
                payload = {
                    "model": self.model_name,
                    "messages": messages,
                    "max_tokens": max_tokens or 1024,
                    "temperature": temperature or 0.7,
                    "top_p": top_p or 0.9,
                    "stream": False,
                    "stop": stop or None
                }
                
                response = await self.http_client.post(
                    "https://api.groq.com/openai/v1/chat/completions",
                    headers=headers,
                    json=payload
                )
                
                if response.status_code == 200:
                    result = response.json()
                    generated_text = result.get("choices", [{}])[0].get("message", {}).get("content", "")
                    return self._clean_response(generated_text)
                else:
                    error_detail = response.text
                    logger.error(f"Groq API error: {response.status_code} - {error_detail}")
                    
                    if response.status_code == 401:
                        logger.warning("🚨 Groq API Key is invalid. FALLING BACK TO OLLAMA (Local Intelligence)...")
                        self.provider = "ollama"
                        self.model_name = self.ollama_model
                        return await self.generate(prompt, max_tokens, temperature, top_p, stop, system_prompt)
                        
                    elif response.status_code == 429:
                        raise RuntimeError("Groq Rate Limit exceeded. Please try again in 1 minute.")
                    elif response.status_code == 400:
                        raise RuntimeError(f"Groq Bad Request (400): {error_detail[:100]}... Possibly invalid model or prompt.")
                    raise RuntimeError(f"Groq API failed with status {response.status_code}")

            
            else:
                # Ollama API call (Local)
                response = await self.http_client.post(
                    f"{self.ollama_base_url}/api/chat",
                    json={
                        "model": self.model_name,
                        "messages": messages,
                        "stream": False,
                        "options": {
                            "num_predict": max_tokens or 1024,
                            "temperature": temperature or 0.7,
                            "top_p": top_p or 0.9,
                            "stop": stop or []
                        }
                    }
                )
                
                if response.status_code == 200:
                    result = response.json()
                    return self._clean_response(result.get("message", {}).get("content", ""))
                else:
                    logger.error(f"Ollama API error: {response.status_code}")
                    return "Processing local intelligence signals..."
                    
        except Exception as e:
            logger.error(f"Generation error: {e}")
            raise RuntimeError(f"AI generation failed: {str(e)}")
    
    async def chat(
        self,
        messages: List[Dict[str, str]],
        max_tokens: Optional[int] = None,
        temperature: Optional[float] = None
    ) -> str:
        """
        Multi-turn chat with conversation history
        """
        if not self._initialized:
            await self.initialize()

        if not self._available:
            raise RuntimeError(f"AI provider '{self.provider}' not available.")
        
        try:
            if self.provider == 'groq':
                headers = {
                    "Authorization": f"Bearer {self.groq_api_key}",
                    "Content-Type": "application/json"
                }
                payload = {
                    "model": self.model_name,
                    "messages": messages,
                    "max_tokens": max_tokens or 1024,
                    "temperature": temperature or 0.7,
                    "stream": False
                }
                
                response = await self.http_client.post(
                    "https://api.groq.com/openai/v1/chat/completions",
                    headers=headers,
                    json=payload
                )
                
                if response.status_code == 200:
                    result = response.json()
                    return self._clean_response(result.get("choices", [{}])[0].get("message", {}).get("content", ""))
                else:
                    raise RuntimeError(f"Groq Chat failed: {response.status_code}")
            
            else:
                response = await self.http_client.post(
                    f"{self.ollama_base_url}/api/chat",
                    json={
                        "model": self.model_name,
                        "messages": messages,
                        "stream": False,
                        "options": {
                            "num_predict": max_tokens or 1024,
                            "temperature": temperature or 0.7
                        }
                    }
                )
                
                if response.status_code == 200:
                    result = response.json()
                    return self._clean_response(result.get("message", {}).get("content", ""))
                else:
                    raise RuntimeError(f"Ollama Chat failed: {response.status_code}")
                    
        except Exception as e:
            logger.error(f"Chat error: {e}")
            raise RuntimeError(f"AI chat failed: {str(e)}")
    
    async def generate_skill_assessment(
        self,
        answer: str,
        question: str,
        correct_answer: str,
        skill: str
    ) -> Dict[str, Any]:
        """
        AI-powered skill assessment for a student's answer
        
        Returns:
            Dict with score, feedback, concept_coverage, depth_analysis
        """
        system_prompt = """You are an expert technical interviewer and educator. 
Evaluate the student's answer with precision and provide constructive feedback.
You must respond ONLY with valid JSON, no other text."""
        
        prompt = f"""Evaluate this answer for a {skill} question:

QUESTION: {question}

CORRECT ANSWER: {correct_answer}

STUDENT'S ANSWER: {answer}

Provide evaluation as JSON:
{{
    "score": <0-100>,
    "concept_understanding": <0-100>,
    "explanation_depth": <0-100>,
    "accuracy": <0-100>,
    "feedback": "<specific constructive feedback>",
    "missing_concepts": ["<concept1>", "<concept2>"],
    "strengths": ["<strength1>", "<strength2>"],
    "improvement_suggestions": ["<suggestion1>", "<suggestion2>"]
}}"""
        
        response = await self.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=500,
            temperature=0.3
        )
        
        try:
            import json
            # Try to extract JSON from response
            start = response.find("{")
            end = response.rfind("}") + 1
            if start != -1 and end > start:
                return json.loads(response[start:end])
        except:
            pass
        
        # Fallback structure
        return {
            "score": 50,
            "concept_understanding": 50,
            "explanation_depth": 50,
            "accuracy": 50,
            "feedback": "Unable to fully evaluate. Please review manually.",
            "missing_concepts": [],
            "strengths": [],
            "improvement_suggestions": ["Practice more questions on this topic"]
        }
    
    async def generate_career_advice(
        self,
        student_profile: Dict[str, Any],
        skill_gaps: List[str],
        target_role: str,
        assessment_results: Dict[str, Any] = {}
    ) -> Dict[str, Any]:
        """
        Generate highly personalized career advice that feels like it's from a real mentor
        """
        # Build unique student identifier for personalization
        student_name = student_profile.get('name', student_profile.get('fullName', 'Student'))
        known_skills = student_profile.get('skills', student_profile.get('knownTechnologies', []))
        experience_level = student_profile.get('experience', student_profile.get('yearOfStudy', 'Fresher'))
        target_companies = student_profile.get('targetCompanies', student_profile.get('preferredCompanies', []))
        
        # Extract operational module (section) performance
        sections = assessment_results.get('sections', assessment_results.get('sectionResults', []))
        module_performance = "\n".join([
            f"- {s.get('name', s.get('section', 'Unknown'))}: {s.get('score', 0)}% ({s.get('correct', 0)}/{s.get('total', 0)} correct)"
            for s in sections
        ]) if sections else "No module-level data available"

        system_prompt = """You are a senior career mentor with 25+ years of experience hiring at top tech companies.
Your advice must be HIGHLY SPECIFIC to this individual student. 
Every piece of advice should reference their actual profile, skills, and goals.
You are NOT giving generic advice - you are consulting for THIS specific person.
Analyze their performance in each technical module (operational module) to suggest the best-fit career paths.
Respond ONLY with valid JSON. No markdown, no explanations outside JSON."""
        
        prompt = f"""Generate personalized career advice and alternative role recommendations for this SPECIFIC student:

🎓 STUDENT PROFILE:
- Name: {student_name}
- Initial Target Role: {target_role}
- Field: {student_profile.get('fieldOfStudy', 'Not specified')}
- Current Skills: {', '.join(known_skills[:10]) if known_skills else 'Not specified'}
- Experience Level: {experience_level}
- Target Companies: {', '.join(target_companies[:5]) if target_companies else 'Top tech companies'}
- Education: {student_profile.get('education', student_profile.get('degree', 'Not specified'))}

📊 OPERATIONAL MODULE PERFORMANCE (ASSESSMENT):
{module_performance}

🔴 IDENTIFIED SKILL GAPS (CRITICAL):
{', '.join(skill_gaps[:5]) if skill_gaps else 'To be analyzed from assessment'}

📋 YOUR TASK:
Generate a career advice JSON that feels like it was written by a mentor who spent hours analyzing {student_name}'s profile and assessment performance.
Do NOT just recommend the initial target role. Based on {student_name}'s strengths in specific modules, recommend 3 distinct career paths.

Respond with JSON:
{{
    "overall_readiness": <0-100 based on skills vs gaps>,
    "personal_message": "A 2-3 sentence personalized message to {student_name} acknowledging their specific situation and assessment performance",
    "career_paths": [
        {{
            "role": "Suggested Job Role (e.g. Frontend Engineer, Data Analyst, etc.)",
            "fit_score": 0-100,
            "why_this_role": "Personalized reason based on {student_name}'s module scores and skills",
            "market_demand": "High/Medium/Low",
            "salary_expectation": "Range based on entry level"
        }}
    ],
    "priority_actions": [
        {{"action": "SPECIFIC action for {student_name}", "timeline": "X days/weeks", "impact": "How this helps get closer to their goals", "details": "Step by step how to do this"}}
    ],
    "skill_development_order": ["skill1 - because {student_name} needs...", "skill2 - since their performance in {random_module} shows..."],
    "daily_routine": {{
        "recommended_hours": X,
        "morning": "What to do",
        "afternoon": "What to do", 
        "evening": "What to do",
        "weekend": "What to do"
    }},
    "interview_preparation_tips": [
        {{"topic": "topic", "tip": "specific tip for {student_name} based on their weaknesses", "resources": "specific resource"}}
    ],
    "resume_suggestions": [
        {{"issue": "what might be weak", "fix": "how to fix", "impact": "why it matters for their top recommended role"}}
    ],
    "confidence_boosters": ["encouragement specific to {student_name}'s journey"],
    "common_mistakes_to_avoid": ["mistake specific to their career phase"],
    "timeline_to_job_ready": "X weeks/months with explanation",
    "target_company_strategy": {{
        "companies": {target_companies[:3] if target_companies else ['Top Tech Firms']},
        "approach": "How {student_name} should approach these companies",
        "when_to_apply": "Timing advice",
        "preparation_checklist": ["item1", "item2"]
    }},
    "next_steps_this_week": ["Very specific action for Monday", "action for midweek", "end of week milestone"]
}}"""

        
        response = await self.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=1200,
            temperature=0.6
        )
        
        try:
            import json
            start = response.find("{")
            end = response.rfind("}") + 1
            if start != -1 and end > start:
                return json.loads(response[start:end])
        except:
            pass
        
        # Enhanced fallback with more specific content
        return {
            "overall_readiness": 50,
            "personal_message": f"Hi {student_name}! Based on your profile, I can see you're working towards becoming a {target_role}. Let's create a plan to get you there.",
            "priority_actions": [
                {"action": f"Master your weakest skill: {skill_gaps[0] if skill_gaps else 'fundamentals'}", "timeline": "2 weeks", "impact": f"Critical for {target_role} interviews", "details": "Start with basics, then practice problems daily"}
            ],
            "skill_development_order": skill_gaps[:3] if skill_gaps else ["Data Structures", "Algorithms", "System Design"],
            "daily_routine": {
                "recommended_hours": 3,
                "morning": "30 min concept study",
                "afternoon": "1 hour problem solving",
                "evening": "1 hour project work",
                "weekend": "Mock interviews and revision"
            },
            "interview_preparation_tips": [{"topic": "Technical", "tip": "Practice explaining your thought process out loud", "resources": "LeetCode, Pramp"}],
            "resume_suggestions": [{"issue": "May lack projects", "fix": "Add 2-3 solid projects with GitHub links", "impact": "Shows practical skills"}],
            "confidence_boosters": [f"You're taking the right steps, {student_name}! Every successful {target_role} started exactly where you are."],
            "common_mistakes_to_avoid": ["Jumping to advanced topics before mastering basics", "Not practicing actual interview scenarios"],
            "timeline_to_job_ready": "6-8 weeks with consistent effort",
            "target_company_strategy": {
                "companies": target_companies[:3] if target_companies else ["Top companies"],
                "approach": "Start with off-campus applications while preparing",
                "when_to_apply": "After completing 2 weeks of focused preparation",
                "preparation_checklist": ["Strong resume", "2+ portfolio projects", "DSA practice", "Mock interviews"]
            },
            "next_steps_this_week": [
                f"Monday: Assess current {skill_gaps[0] if skill_gaps else 'coding'} level",
                "Wednesday: Complete 5 practice problems",
                "Saturday: Build a small feature for portfolio"
            ]
        }
    
    async def chat_with_student(
        self,
        message: str,
        conversation_history: List[Dict[str, str]],
        student_context: Dict[str, Any]
    ) -> str:
        """
        Interactive chat with AI mentor - fully generative, no hardcoded responses
        """
        # Build comprehensive system prompt with full student context
        style_hints = student_context.get('style_hints', [])
        style_instructions = "\n".join([f"- {hint}" for hint in style_hints]) if style_hints else "Maintain a supportive, encouraging tone."
        
        # Determine engagement level
        interaction_count = student_context.get('interaction_count', 0)
        engagement_note = ""
        if interaction_count == 0:
            engagement_note = "This is a NEW student - introduce yourself warmly and learn about their goals."
        elif interaction_count < 5:
            engagement_note = "This student is still getting to know you - be extra helpful and encouraging."
        else:
            engagement_note = "You have an established relationship with this student - reference past conversations when relevant."
        
        system_prompt = f"""You are Prepzo AI Mentor, an elite career guidance assistant with the personality of a supportive senior developer and expert career coach.

🎯 YOUR MISSION: Help this specific student succeed in their career journey.

📊 STUDENT CONTEXT (USE THIS TO PERSONALIZE EVERY RESPONSE):
- Name: {student_context.get('name', 'Student')}
- Target Role: {student_context.get('target_role', 'Software Engineer')}
- Current Skill Level: {student_context.get('skill_level', 'Intermediate')}
- Last Assessment Score: {student_context.get('last_assessment_score', 'Not yet assessed')}%
- Weak Areas (FOCUS ON THESE): {', '.join(student_context.get('weak_areas', ['Not yet identified'])[:5])}
- Strong Areas (BUILD ON THESE): {', '.join(student_context.get('strong_areas', ['Not yet identified'])[:3])}
- Learning Streak: {student_context.get('learning_streak', 0)} days
- Communication Style: {student_context.get('personality_traits', {}).get('communication_style', 'balanced')}

💡 STYLE INSTRUCTIONS:
{style_instructions}

📝 ENGAGEMENT NOTE:
{engagement_note}

🚀 RESPONSE GUIDELINES:
1. ALWAYS reference the student's specific situation (weak areas, target role, score)
2. Be conversational and human - you're a mentor, not a textbook
3. Provide actionable advice with clear next steps
4. When the student is stuck, break down the problem into smaller parts
5. Celebrate their progress, no matter how small
6. End responses with a question or call-to-action to keep them engaged
7. Use emojis sparingly to add warmth (1-2 per response max)

REMEMBER: You know this student - speak to THEM specifically, not to a generic student."""
        
        # Build conversation context
        messages = [{"role": "system", "content": system_prompt}]
        
        # Add conversation history
        for msg in conversation_history[-10:]:
            messages.append({
                "role": msg.get("role", "user"),
                "content": msg.get("content", "")
            })
        
        # Add current message
        messages.append({"role": "user", "content": message})
        
        return await self.chat(messages, max_tokens=600, temperature=0.75)
    

    @property
    def _ollama_available(self) -> bool:
        """Alias for _available used by legacy parts of QuestionGenerator"""
        return self._available

    @property
    def is_ready(self) -> bool:
        """Check if model service is ready for inference"""
        return self._initialized and self._available
