# pyre-ignore-all-errors
"""
AI Question Generation Engine — Prepzo
========================================
100% LLM-driven. No hardcoded questions ever.
Every student gets unique, personalized, adaptive questions.
"""

import asyncio
import json
import re
import random
import hashlib
from datetime import datetime
from typing import List, Dict, Any, Optional, cast
from loguru import logger  # type: ignore


class QuestionGenerator:
    """
    Core AI Question Generator.

    Rules (strictly enforced):
    • ZERO hardcoded questions
    • EVERY question is generated by Ollama LLM at runtime
    • Unique per student per attempt (timestamp + random salt in prompt)
    • Adaptive difficulty based on live performance
    • Profile-aware (field, degree, targetRole, skills, year)
    """

    # ──────────────────────────────────────────────────────────────────────────
    # Configuration tables  (metadata only — no questions stored here)
    # ──────────────────────────────────────────────────────────────────────────

    STREAM_SECTIONS: Dict[str, Dict[str, List[str]]] = {
        "computer_science": {
            "DSA":           ["Arrays & Hashing", "Two Pointers", "Sliding Window", "Stacks & Queues",
                              "Binary Search", "Linked Lists", "Trees & BST", "Graphs & BFS/DFS",
                              "Dynamic Programming", "Recursion & Backtracking", "Heaps & Priority Queues",
                              "Sorting Algorithms", "Tries", "Greedy Algorithms"],
            "DBMS":          ["ACID Properties", "Normalization (1NF-BCNF)", "SQL Queries & Joins",
                              "Indexing & B-Trees", "Transactions & Locking", "Concurrency Control",
                              "Query Optimization", "NoSQL vs RDBMS", "ER Diagrams", "Stored Procedures"],
            "OS":            ["Process vs Thread", "CPU Scheduling Algorithms", "Memory Management & Paging",
                              "Deadlock Detection & Prevention", "Virtual Memory & TLB",
                              "File Systems & Inodes", "Semaphores & Mutexes", "Interrupt Handling",
                              "System Calls", "Context Switching"],
            "CN":            ["OSI Model Layers", "TCP vs UDP", "HTTP/HTTPS & REST", "DNS & CDN",
                              "IP Addressing & Subnetting", "Routing Protocols (OSPF, BGP)",
                              "TLS/SSL Handshake", "Load Balancing", "WebSockets", "NAT & Firewalls"],
            "OOPS":          ["Encapsulation", "Inheritance & Polymorphism", "Abstraction & Interfaces",
                              "SOLID Principles", "Design Patterns (Singleton, Factory, Observer)",
                              "Composition vs Inheritance", "Abstract Classes", "Method Overriding",
                              "Generics & Templates", "Exception Handling"],
            "System Design": ["Scalability & Load Balancing", "CAP Theorem", "Caching (Redis, Memcached)",
                              "Message Queues (Kafka, RabbitMQ)", "Microservices Architecture",
                              "Database Sharding & Replication", "Rate Limiting", "CDN & Edge Computing",
                              "Consistent Hashing", "Event-Driven Architecture"],
            "Aptitude":      ["Time & Work", "Permutations & Combinations", "Probability",
                              "Logical Reasoning Sequences", "Data Interpretation", "Number Series",
                              "Profit & Loss", "Ages Problems", "Blood Relations", "Seating Arrangements"],
        },
        "mechanical": {
            "Thermodynamics": ["Laws of Thermodynamics", "Carnot Cycle", "Entropy & Enthalpy", "Heat Transfer & Refrigeration", "Internal Combustion Engines", "Power Plant Engineering"],
            "Mechanics":      ["Statics & Dynamics", "Rotational Motion", "Fluid Mechanics & Machines", "Kinematics of Machinery", "Stress & Strain", "Machine Design Fundamentals"],
            "Manufacturing":  ["Casting & Welding", "CNC Machining", "Tolerances & Limits", "Quality Control (SQD)", "Metal Forming", "Modern Manufacturing Processes"],
            "Design":         ["CAD/CAM Principles", "Materials Science", "Vibrations & Control", "Solid Mechanics", "Mechanisms Design"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Data Interpretation", "Abstract Reasoning"],
        },
        "electrical": {
            "Circuits":      ["Kirchhoff's Laws", "Thevenin & Norton Theorems", "AC Circuit Analysis", "Power Factor Correction", "Network Theorems & Resonance"],
            "Machines":      ["DC & AC Machines", "Transformers", "Induction & Synchronous Motors", "Power Systems Analysis", "Protection & Switchgear"],
            "Electronics":   ["Semiconductor Physics", "Op-Amps & Linear ICs", "Digital Logic Gates", "ADC/DAC Converters", "Microprocessors (8085/8086)", "BJT & MOSFET Analysis"],
            "Embedded":      ["Microcontrollers (8051/ARM)", "Real-Time Operating Systems (RTOS)", "Embedded C Programming", "Peripheral Interfacing", "FPGA & VHDL"],
            "Signals":       ["Fourier & Z-Transforms", "LTI Systems", "Signal Processing", "Communication Systems", "Modulation Techniques"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Data Interpretation", "Engineering Math"],
        },
        "civil": {
            "Structures":     ["Structural Analysis", "RCC & Pre-stressed Design", "Steel Structures Design", "Strength of Materials", "Structural Dynamics"],
            "Geotechnical":   ["Soil Mechanics & Classification", "Foundation Engineering", "Earth Pressure & Retaining Walls", "Slope Stability", "Soil Compaction"],
            "Hydraulics":     ["Fluid Mechanics", "Open Channel Flow", "Hydrology & Precipitation", "Irrigation Engineering", "Water Resources Management"],
            "Surveying":      ["GPS & Remote Sensing", "Leveling & Contouring", "Theodolite Surveying", "Curve Setting", "Estimation & Costing"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Spatial Reasoning"],
        },
        "management": {
            "Marketing":      ["Marketing Mix (4Ps & 7Ps)", "Consumer Behavior & STP", "Digital & Social Media Marketing", "Market Research Methods", "Brand Management & Equity"],
            "Finance":        ["Financial Management & Statement Analysis", "Capital Budgeting Techniques", "Working Capital Management", "Risk & Return Analysis", "Financial Ratios & Portfolios"],
            "HR":             ["Recruitment & Selection", "Training & Development", "Performance Appraisals", "Organizational Behavior", "Labor Laws & Industrial Relations"],
            "Ops":            ["Supply Chain Management", "Inventory Control (EOQ/JIT)", "Operations Research (LP)", "Project Management (CPM/PERT)", "Total Quality Management (TQM)"],
            "Strategy":       ["SWOT & PESTLE Analysis", "Porter's Five Forces", "Business Strategy Formulation", "Competitive Advantage", "Corporate Governance"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Business Case Analysis", "Data Interpretation"],
        },
        "iot": {
            "Sensors":        ["Sensor Types & Working", "Actuators & Transducers", "Signal Conditioning", "Calibration & Accuracy", "Smart Sensors"],
            "Connectivity":   ["Wireless Protocols (Zigbee, LoRa)", "Bluetooth & BLE", "Wi-Fi & Cellular IoT", "Network Topologies", "Communication Standards"],
            "Protocols":      ["MQTT & CoAP", "HTTP/REST in IoT", "AMQP & XMPP", "Data Serialization (JSON/Protobuf)", "Edge Computing Protocols"],
            "Robotics":       ["Robot Kinematics", "Motion planning", "Control Systems", "Computer Vision for Robots", "AI in Robotics"],
            "Security":       ["IoT Security Frameworks", "Encryption & Key Management", "Privacy in IoT", "Secure Boot & Firmware", "Blockchain in IoT"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "System Thinking"],
        },
        "commerce": {
            "Accounting":     ["Financial Accounting Principles", "Corporate Accounting", "Cost & Management Accounting", "Auditing & Assurance", "IFRS & Ind-AS"],
            "Taxation":       ["Income Tax (Heads of Income)", "GST Framework", "Corporate Tax Planning", "TDS & Return Filing", "Customs & International Tax"],
            "Economics":      ["Micro & Macro Economics", "Public Finance", "Industrial Economics", "International Trade Theory", "Banking & Monetary Policy"],
            "Law":            ["Business Law", "Company Law", "Contract Act", "Intellectual Property Rights", "Consumer Protection"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Business Arithmetic"],
        },
        "science": {
            "CoreScience":    ["Scientific Method & Hypothesis", "Research Methodology", "Data Analysis & Statistics", "Theoretical Models", "Lab Safety & Protocols"],
            "AppliedScience": ["Biotechnology Applications", "Nanotechnology Basics", "Environmental Science & Sustainability", "Space Research & Astronomy", "Renewable Energy"],
            "Data":           ["Statistical Inference", "Probability Theory", "Experimental Design", "Data Visualization", "Big Data in Science"],
            "Aptitude":       ["Quantitative Aptitude", "Logical Reasoning", "Verbal Ability", "Abstract Reasoning"],
        },
        "arts": {
            "Humanities":     ["Political Science Theory", "Psychology & Behavioral Science", "Sociology & Social Change", "Global History & Heritage", "Literature & Criticism"],
            "Expression":     ["Creative writing & Media Ethics", "Communication Skills & Linguistics", "Mass Media & Journalism", "Philosophy & Ethics", "Visual Arts & Aesthetics"],
            "Social":         ["Public Policy", "Social Research Methods", "Geography & Demographics", "Anthropology", "International Relations"],
            "Aptitude":       ["Verbal Ability & Reading Comprehension", "Logical Reasoning", "General Awareness", "Creative & Lateral Thinking"],
        },
    }

    COMPANY_PATTERNS: Dict[str, Dict[str, Any]] = {
        "amazon":    {"sections": ["DSA", "System Design", "OOPS", "Aptitude"],
                      "dist": {"easy": 0.10, "medium": 0.50, "hard": 0.30, "advanced": 0.10},
                      "focus": "Optimal solutions, scalable systems, leadership principles",
                      "style": "Problem-solving with clear trade-off discussions"},
        "google":    {"sections": ["DSA", "System Design", "Aptitude", "CN"],
                      "dist": {"easy": 0.10, "medium": 0.35, "hard": 0.40, "advanced": 0.15},
                      "focus": "Algorithmic thinking, clean code, complexity analysis",
                      "style": "Multiple solutions, time-space complexity discussion"},
        "microsoft": {"sections": ["DSA", "OOPS", "System Design", "OS"],
                      "dist": {"easy": 0.15, "medium": 0.45, "hard": 0.30, "advanced": 0.10},
                      "focus": "Object-oriented design, system thinking, problem breakdown",
                      "style": "Design questions with edge case handling"},
        "tcs":       {"sections": ["Aptitude", "DBMS", "CN", "DSA"],
                      "dist": {"easy": 0.35, "medium": 0.45, "hard": 0.15, "advanced": 0.05},
                      "focus": "Programming fundamentals, aptitude, reasoning",
                      "style": "MCQ-heavy, time-bound, NQT pattern"},
        "infosys":   {"sections": ["Aptitude", "OOPS", "DBMS", "DSA"],
                      "dist": {"easy": 0.35, "medium": 0.45, "hard": 0.15, "advanced": 0.05},
                      "focus": "Logical reasoning, programming basics, spoken English",
                      "style": "Aptitude + coding, InfyTQ pattern"},
        "wipro":     {"sections": ["Aptitude", "CN", "DBMS", "DSA"],
                      "dist": {"easy": 0.35, "medium": 0.45, "hard": 0.15, "advanced": 0.05},
                      "focus": "Communication skills, fundamentals, reasoning",
                      "style": "Online assessment + coding challenges"},
        "accenture": {"sections": ["Aptitude", "OOPS", "DSA", "DBMS"],
                      "dist": {"easy": 0.30, "medium": 0.50, "hard": 0.15, "advanced": 0.05},
                      "focus": "Problem solving, adaptability, cognitive assessment",
                      "style": "Game-based + coding challenges"},
    }

    DIFFICULTY_ORDER = ["easy", "medium", "hard", "advanced"]

    # ──────────────────────────────────────────────────────────────────────────
    # Initialisation
    # ──────────────────────────────────────────────────────────────────────────

    def __init__(self, model_service=None):
        self.model_service = model_service
        self._initialized = False
        self._semaphore = asyncio.Semaphore(5)  # Limit concurrent LLM calls

    async def _ensure_model(self):
        """Lazy initialise and inject model service from app state."""
        if self.model_service is not None:
            return

        # Import here to avoid circular imports
        try:
            from app.main import model_service  # type: ignore
            self.model_service = model_service
        except Exception:
            pass

        if self.model_service is None:
            try:
                from app.services.model_service import ModelService  # type: ignore
                self.model_service = ModelService()
                await self.model_service.initialize()
            except Exception as exc:
                logger.error(f"Could not initialise ModelService: {exc}")

    # ──────────────────────────────────────────────────────────────────────────
    # Helpers
    # ──────────────────────────────────────────────────────────────────────────

    @staticmethod
    def _trunc(s: str, n: int) -> str:
        """Return first *n* characters of *s*.  Isolated helper to avoid Pyre2 slice false-positives."""
        return str(s)[:n]  # pyre-ignore[16]

    @staticmethod
    def _ltrunc(lst: list, n: int) -> list:  # type: ignore[type-arg]
        """Return first *n* items of *lst*."""
        return list(lst)[:n]  # pyre-ignore[16]

    def _unique_seed(self, profile: Dict[str, Any]) -> str:
        raw = f"{profile.get('id', '')}-{datetime.utcnow().isoformat()}-{random.random()}"
        return hashlib.md5(raw.encode()).hexdigest()

    def _stream_category(self, profile: Dict[str, Any]) -> str:
        s = (profile.get("fieldOfStudy") or profile.get("stream") or "").lower()
        if any(k in s for k in ["mechanical", "mech"]):
            return "mechanical"
        if any(k in s for k in ["electrical", "ece", "eee", "electronics"]):
            return "electrical"
        if any(k in s for k in ["iot", "robotics", "mechatronics"]):
            return "iot"
        if "civil" in s:
            return "civil"
        if any(k in s for k in ["mba", "bba", "management", "business", "pgdm"]):
            return "management"
        if any(k in s for k in ["bcom", "commerce", "accounting", "taxation"]):
            return "commerce"
        if any(k in s for k in ["bsc", "msc", "science", "physics", "chemistry", "biology", "math"]):
            return "science"
        if any(k in s for k in ["ba", "ma", "arts", "humanities", "sociology", "psychology", "history"]):
            return "arts"
        return "computer_science"

    def _pick_topics(self, stream_cat: str, section: str, profile: Dict[str, Any]) -> List[str]:
        # If the section is a skill the user selected, use it as a custom topic
        skill_ratings = profile.get("skillRatings", {})
        if section in skill_ratings:
            return [section]
        
        # Otherwise use standard topics for the section
        # Map full names to abbreviations used in STREAM_SECTIONS
        section_mapping = {
            "operating systems": "OS",
            "computer networks": "CN",
            "data structures & algorithms": "DSA",
            "data structures": "DSA",
            "algorithms": "DSA",
            "database management systems": "DBMS",
            "dbms": "DBMS",
            "object oriented programming": "OOPS",
            "object oriented programming systems": "OOPS"
        }
        
        normalized_section = section_mapping.get(section.lower(), section)
        
        # Get topics from stream config, fallback to section name if not found
        sections_config = self.STREAM_SECTIONS.get(stream_cat, {})
        topics = sections_config.get(normalized_section, [section])
        
        return topics

    def _difficulty_counts(self, n: int, dist: Dict[str, float]) -> Dict[str, int]:
        safe_n = max(1, int(n) if n is not None else 1)
        counts: Dict[str, int] = {d: max(0, int(safe_n * float(dist.get(d) if dist.get(d) is not None else 0))) for d in self.DIFFICULTY_ORDER}
        deficit = safe_n - sum(counts.values())
        counts["hard"] = max(0, counts["hard"] + deficit) # Prioritize hard for deficits
        return counts

    @staticmethod
    def _parse_json(raw: str) -> Optional[Dict[str, Any]]:
        """Robustly extract first JSON object from model output."""
        if not raw:
            return None
            
        # Try to find JSON block in markdown
        for pattern in (
            r"```(?:json)?\s*([\s\S]*?)\s*```",
            r"(\{[\s\S]*\})",
        ):
            m = re.search(pattern, raw)
            if m:
                candidate = m.group(1).strip()
                try:
                    # Clean up common model hallucinations in JSON
                    # Replace single quotes with double quotes (rough heuristic)
                    cleaned = candidate.replace("'", '"')
                    # Remove trailing commas before closing braces/brackets
                    cleaned = re.sub(r',\s*\}', '}', cleaned)
                    cleaned = re.sub(r',\s*\]', ']', cleaned)
                    # Handle unescaped newlines in strings (very common in 1B models)
                    cleaned = re.sub(r'(?<!\\)\n', ' ', cleaned)
                    return json.loads(cleaned)
                except json.JSONDecodeError:
                    # Try raw candidate if cleaning failed
                    try:
                        return json.loads(candidate)
                    except json.JSONDecodeError:
                        pass

        # Last-ditch: find the outermost { }
        start = raw.find("{")
        end = raw.rfind("}") + 1
        if start != -1 and end > start:
            try:
                candidate = str(raw)[start:end]
                # Same cleaning for last-ditch
                cleaned = re.sub(r'(?<!\\)\n', ' ', candidate)
                cleaned = re.sub(r',\s*\}', '}', cleaned)
                return json.loads(cleaned)
            except json.JSONDecodeError:
                pass
        return None

    # ──────────────────────────────────────────────────────────────────────────
    # LLM call wrapper
    # ──────────────────────────────────────────────────────────────────────────

    async def _llm(self, prompt: str, max_tokens: int = 1000, temperature: float = 0.85) -> str:
        """Call the Ollama model with concurrency control; raise if unavailable."""
        await self._ensure_model()
        if self.model_service is None or not self.model_service.has_model:
            raise RuntimeError("Ollama model not available. Ensure Ollama is running.")
        
        async with self._semaphore:
            return await self.model_service.generate(prompt, max_tokens=max_tokens, temperature=temperature)

    # ──────────────────────────────────────────────────────────────────────────
    # Prompts Optimized for Small Models (1B-8B)
    # ──────────────────────────────────────────────────────────────────────────

    def _mcq_prompt(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> str:
        return f"""Generate 1 multiple-choice question for a technical interview at {company.upper() or 'a tech company'}.

CONTEXT: {profile_ctx}
SECTION: {section}
TOPIC: {topic}
DIFFICULTY: {difficulty.upper()}
CATEGORY: {category.upper() if category else 'TECHNICAL'}

STRICT INSTRUCTION:
{ 'Generate a theoretical, foundational, or principled question focusing on core concepts and underlying mechanics.' if category == 'foundational' else 'Generate a practical, applied, or skill-specific question focusing on real-world implementation, debugging, or deep technical depth.' if category == 'practical' else 'Generate a comprehensive technical interview question.' }

The question should be technical and challenging. Respond ONLY with a JSON object in this format:
{{
  "question": "question text",
  "options": ["option A", "option B", "option C", "option D"],
  "correct": 0,
  "explanation": "why A is correct",
  "topic": "{topic}",
  "difficulty": "{difficulty}"
}}"""

    def _coding_prompt(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> str:
        return f"""Task: Generate 1 coding problem for {company.upper()}.
Topic: {topic}
Difficulty: {difficulty.upper()}
Category: {category.upper() if category else 'TECHNICAL'}

STRICT INSTRUCTION:
{ 'Focus on whiteboard-style conceptual implementation, data structure principles, and logic.' if category == 'foundational' else 'Focus on industrial-grade implementation, handling edge cases, optimization for production, and skill-specific complex scenarios.' if category == 'practical' else 'Generate a challenging coding problem.' }

Stictly respond with ONLY JSON:
{{
  "title": "Problem Title",
  "description": "Problem statement",
  "inputFormat": "...",
  "outputFormat": "...",
  "constraints": ["..."],
  "examples": [
    {{"input": "...", "output": "...", "explanation": "..."}}
  ],
  "hiddenTestCases": [
    {{"input": "...", "output": "..."}}
  ],
  "expectedComplexity": {{"time": "O(n)", "space": "O(1)"}},
  "starterCode": {{
    "python": "def solution(n):\n    pass"
  }}
}}"""

    def _short_answer_prompt(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> str:
        return f"""Generate a high-level system design or architectural interview question asked at {company.upper() or 'Microsoft/Meta'}.

STUDENT CONTEXT:
{profile_ctx}

TOPIC: {topic}
DIFFICULTY: {difficulty.upper()}
CATEGORY: {category.upper() if category else 'TECHNICAL'}

STRICT INSTRUCTION:
{ 'Analyze theoretical trade-offs, foundational architectures, and academic concepts.' if category == 'foundational' else 'Analyze practical system bottlenecks, real-world deployment challenges, and skill-specific troubleshooting.' if category == 'practical' else 'Analyze deep trade-offs, scalability, or performance bottlenecks.' }

STRICT RULES:
- Ask about deep trade-offs, scalability, or performance bottlenecks.
- The student must provide a nuanced technical response.

Respond with ONLY this JSON:
{{
  "question": "<scenario-based architectural or system design question>",
  "expectedAnswer": "<points for a perfect score>",
  "rubric": {{
    "excellent": "Nuanced understanding of constraints",
    "good": "Covers basic trade-offs",
    "poor": "Generic or incorrect"
  }},
  "keywords": ["<key-term1>", "<key-term2>"],
  "topic": "{topic}",
  "difficulty": "{difficulty}",
  "companyAskedIn": "{company.upper() or 'Various'}"
}}"""

    # ──────────────────────────────────────────────────────────────────────────
    # Single question generation
    # ──────────────────────────────────────────────────────────────────────────

    async def _gen_mcq(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> dict:
        prompt = self._mcq_prompt(section, topic, difficulty, profile_ctx, company, seed, idx, category)
        for attempt in range(3):
            try:
                raw = await self._llm(prompt, max_tokens=800, temperature=0.85 + (attempt * 0.05))
                data = self._parse_json(raw)
                if data and "question" in data and "options" in data and len(data["options"]) == 4:
                    seed8 = self._trunc(seed, 8)
                    return {
                        "id": f"mcq_{seed8}_{idx}",
                        "type": "mcq",
                        "section": section,
                        "topic": topic,
                        "difficulty": difficulty,
                        "question": data["question"],
                        "options": data["options"],
                        "correct": int(data.get("correct") if data.get("correct") is not None else 0) % 4,
                        "explanation": data.get("explanation", ""),
                        "conceptsTested": data.get("conceptsTested", [topic]),
                        "companyAskedIn": data.get("companyAskedIn", company.upper() or "Top Tech firms"),
                        "aiGenerated": True,
                        "uniqueSeed": seed8,
                    }
            except Exception as exc:
                if attempt == 2:
                    logger.debug(f"Last MCQ attempt raw output: {raw if 'raw' in locals() else 'N/A'}")
                logger.warning(f"MCQ generation failed for {section}/{topic} (attempt {attempt+1}): {exc}")
                
        # Return None instead of raising to allow section to contain other valid questions
        return None

    async def _gen_coding(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> dict:
        prompt = self._coding_prompt(section, topic, difficulty, profile_ctx, company, seed, idx, category)
        for attempt in range(3):
            try:
                raw = await self._llm(prompt, max_tokens=1500, temperature=0.82 + (attempt * 0.05))
                data = self._parse_json(raw)
                if data and "title" in data and "description" in data:
                    seed8 = self._trunc(seed, 8)
                    return {
                        "id": f"code_{seed8}_{idx}",
                        "type": "coding",
                        "section": section,
                        "topic": topic,
                        "difficulty": difficulty,
                        "title": data.get("title", "Coding Problem"),
                        "question": data.get("description", ""),
                        "description": data.get("description", ""),
                        "inputFormat": data.get("inputFormat", ""),
                        "outputFormat": data.get("outputFormat", ""),
                        "constraints": data.get("constraints", []),
                        "examples": data.get("examples", []),
                        "hiddenTestCases": data.get("hiddenTestCases", []),
                        "expectedComplexity": data.get("expectedComplexity", {"time": "O(n)", "space": "O(1)"}),
                        "starterCode": data.get("starterCode", {}),
                        "conceptsTested": data.get("conceptsTested", [topic]),
                        "companyAskedIn": data.get("companyAskedIn", company.upper() or "Top Tech firms"),
                        "options": [],
                        "correct": -1,
                        "aiGenerated": True,
                        "uniqueSeed": seed8,
                    }
            except Exception as exc:
                if attempt == 2:
                    logger.debug(f"Last Coding attempt raw output: {raw if 'raw' in locals() else 'N/A'}")
                logger.warning(f"Coding generation failed for {section}/{topic} (attempt {attempt+1}): {exc}")

        return None

    async def _gen_short_answer(self, section: str, topic: str, difficulty: str, profile_ctx: str, company: str, seed: str, idx: int, category: str = "") -> dict:
        prompt = self._short_answer_prompt(section, topic, difficulty, profile_ctx, company, seed, idx, category)
        for attempt in range(3):
            try:
                raw = await self._llm(prompt, max_tokens=900, temperature=0.80 + (attempt * 0.05))
                data = self._parse_json(raw)
                if data and "question" in data:
                    seed8 = self._trunc(seed, 8)
                    return {
                        "id": f"short_{seed8}_{idx}",
                        "type": "short_answer",
                        "section": section,
                        "topic": topic,
                        "difficulty": difficulty,
                        "question": data["question"],
                        "expectedAnswer": data.get("expectedAnswer", ""),
                        "rubric": data.get("rubric", {}),
                        "keywords": data.get("keywords", []),
                        "conceptsTested": data.get("conceptsTested", [topic]),
                        "companyAskedIn": data.get("companyAskedIn", company.upper() or "Top Tech firms"),
                        "options": [],
                        "correct": -1,
                        "aiGenerated": True,
                        "uniqueSeed": seed8,
                    }
            except Exception as exc:
                logger.warning(f"Short-answer generation failed for {section}/{topic} (attempt {attempt+1}): {exc}")

        return None

    # ──────────────────────────────────────────────────────────────────────────
    # Question type selector
    # ──────────────────────────────────────────────────────────────────────────

    def _question_type(self, section: str, difficulty: str, idx: int) -> str:
        sl = section.lower()
        if sl in ("coding", "dsa", "problem solving", "algorithms"):
            if difficulty in ("hard", "advanced"):
                return "coding"
            if idx % 3 == 0:
                return "coding"
        if idx % 5 == 0 and sl not in ("aptitude",):
            return "short_answer"
        return "mcq"

    # ──────────────────────────────────────────────────────────────────────────
    # Context builders
    # ──────────────────────────────────────────────────────────────────────────

    def _profile_context(self, profile: dict) -> str:
        skills = profile.get("knownTechnologies", [])
        # Include specific skill ratings if available
        skill_ratings = profile.get("skillRatings", {})
        ratings_str = ", ".join([f"{k} (Level {v}/10)" for k,v in skill_ratings.items()]) if skill_ratings else "Not specified"
        
        return (
            f"Name       : {profile.get('name', 'Student')}\n"
            f"Degree     : {profile.get('degree', 'B.Tech')}\n"
            f"Stream     : {profile.get('stream', 'Computer Science')}\n"
            f"FieldOfStudy: {profile.get('fieldOfStudy', 'Engineering')}\n"
            f"Year       : {profile.get('year', 'Final Year')}\n"
            f"Target Role: {profile.get('targetRole', 'Software Engineer')}\n"
            f"Skill Ratings: {ratings_str}\n"
            f"Career Goals: {profile.get('careerGoals', 'Placement at top tech company')}"
        )

    def _company_context(self, pattern: dict, company: str) -> str:
        if not pattern:
            # Randomly pick a top company if none specified to add spice
            top_firms = ["Google", "Amazon", "Microsoft", "Meta", "Uber", "Netflix", "Adobe", "Zomato", "Swiggy", "Walmart"]
            random_firm = random.choice(top_firms)
            return f"Company: {random_firm}\nStyle: Challenging Product-based interview"
            
        return (
            f"Company    : {company.upper()}\n"
            f"Style      : {pattern.get('style', '')}\n"
            f"Focus Areas: {pattern.get('focus', '')}"
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Section-level generation
    # ──────────────────────────────────────────────────────────────────────────

    async def _generate_section(self, section: str, profile: dict, num_q: int, dist: dict, seed: str, stream_cat: str, company_pattern: dict = None, company: str = "", category: str = "") -> list:
        topics: List[str] = self._pick_topics(stream_cat, section, profile)
        profile_ctx = self._profile_context(profile)
        
        # If no specific company requested, we will rotate between top-tier firms in the prompt
        top_firms = ["Amazon", "Google", "Microsoft", "Adobe", "Uber", "Zomato", "Goldman Sachs", "Intuit", "Directi", "Slice"]
        
        counts: Dict[str, int] = self._difficulty_counts(num_q, dist)
        tasks = []
        q_idx = 0
        for difficulty in self.DIFFICULTY_ORDER:
            count_for_diff: int = counts.get(difficulty, 0)
            for _i in range(count_for_diff):
                t_idx: int = q_idx % max(1, len(topics))  # pyre-ignore[58]
                topic: str = topics[t_idx]
                qtype = self._question_type(section, difficulty, q_idx)
                target_company = company if company else random.choice(top_firms)

                if qtype == "coding":
                    tasks.append(self._gen_coding(section, topic, difficulty, profile_ctx, target_company, seed, q_idx, category))
                elif qtype == "short_answer":
                    tasks.append(self._gen_short_answer(section, topic, difficulty, profile_ctx, target_company, seed, q_idx, category))
                else:
                    tasks.append(self._gen_mcq(section, topic, difficulty, profile_ctx, target_company, seed, q_idx, category))
                q_idx += 1

        # Generate questions in small batches (chunks) to prevent timeouts on Render
        results = []
        chunk_size = 5
        for i in range(0, len(tasks), chunk_size):
            chunk = tasks[i : i + chunk_size]
            batch_results = await asyncio.gather(*chunk, return_exceptions=True)
            results.extend(batch_results)
            # Yield control back to ensure event loop stays alive
            await asyncio.sleep(0.2)
        
        questions: List[Dict[str, Any]] = []
        for i, res in enumerate(results):
            if isinstance(res, Exception) or res is None:
                # Slot-based recovery: if AI failed this specific question, inject a safety one immediately
                logger.warning(f"  → Question slot {i} failed in {section}. Injecting safety fallback.")
                
                safety_qs = self._get_safety_questions(section, 1, seed)
                if safety_qs:
                    questions.append(safety_qs[0])
                continue
                
            if isinstance(res, dict):
                questions.append(res)

        # Final check - ensure we at least have 3 questions per section
        if len(questions) < 3:
            logger.warning(f"  → AI failed to produce minimum questions for {section}. Filling from safety net.")
            missing = max(0, 3 - len(questions))
            if missing > 0:
                safety = self._get_safety_questions(section, missing, seed)
                questions.extend(safety)
            
        return questions

    def _get_safety_questions(self, section: str, count: int, seed: str) -> List[Dict[str, Any]]:
        """Provides a small set of high-quality predefined questions as a safety net."""
        seed8 = self._trunc(seed, 8)
        
        # Categorized safety questions
        safety_net = {
            "DSA": [
                {
                    "id": f"safe_dsa_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "What is the time complexity of searching for an element in a balanced Binary Search Tree (BST)?",
                    "options": ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
                    "correct": 2,
                    "explanation": "In a balanced BST, the height is log(n), so searching takes O(log n) time.",
                    "topic": "Trees",
                    "difficulty": "medium",
                    "aiGenerated": False
                },
                {
                    "id": f"safe_dsa_{seed8}_2",
                    "type": "coding",
                    "section": section,
                    "title": "Reverse Linked List",
                    "description": "Given the head of a singly linked list, reverse the list, and return the reversed list.",
                    "inputFormat": "ListNode head",
                    "outputFormat": "ListNode reversedHead",
                    "constraints": ["Number of nodes is [0, 5000]", "-5000 <= node.val <= 5000"],
                    "examples": [{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]"}],
                    "hiddenTestCases": [{"input": "[1,2]", "output": "[2,1]"}],
                    "expectedComplexity": {"time": "O(n)", "space": "O(1)"},
                    "starterCode": {"python": "class Solution:\n    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:\n        pass"},
                    "aiGenerated": False
                }
            ],
            "Aptitude": [
                {
                    "id": f"safe_apt_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "If a train 150m long passes a pole in 15 seconds, what is its speed in km/h?",
                    "options": ["30 km/h", "36 km/h", "45 km/h", "50 km/h"],
                    "correct": 1,
                    "explanation": "Speed = Distance / Time = 150/15 = 10 m/s. Converting to km/h: 10 * (18/5) = 36 km/h.",
                    "topic": "Quantitative",
                    "difficulty": "medium",
                    "aiGenerated": False
                },
                {
                    "id": f"safe_apt_{seed8}_2",
                    "type": "mcq",
                    "section": section,
                    "question": "The average of 5 consecutive numbers is 20. What is the largest of these numbers?",
                    "options": ["21", "22", "23", "24"],
                    "correct": 1,
                    "explanation": "If average is 20, the middle number is 20. The numbers are 18, 19, 20, 21, 22. Largest is 22.",
                    "topic": "Averages",
                    "difficulty": "easy",
                    "aiGenerated": False
                }
            ],
            "CS Fundamentals": [
                {
                    "id": f"safe_cs_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "Which of the following is not a pillar of Object-Oriented Programming?",
                    "options": ["Encapsulation", "Polymorphism", "Recursion", "Inheritance"],
                    "correct": 2,
                    "explanation": "The four pillars are Encapsulation, Inheritance, Polymorphism, and Abstraction. Recursion is a programming technique.",
                    "topic": "OOPS",
                    "difficulty": "beginner",
                    "aiGenerated": False
                },
                {
                    "id": f"safe_cs_{seed8}_2",
                    "type": "mcq",
                    "section": section,
                    "question": "In compilation, what is the role of a Lexical Analyzer?",
                    "options": ["Syntax checking", "Converting code to tokens", "Memory allocation", "Linker optimization"],
                    "correct": 1,
                    "explanation": "Lexical analysis is the first phase of a compiler where it reads characters and produces tokens.",
                    "topic": "Compilers",
                    "difficulty": "medium",
                    "aiGenerated": False
                }
            ],
            "DBMS": [
                {
                    "id": f"safe_db_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "Which SQL keyword is used to sort the result-set?",
                    "options": ["SORT BY", "ORDER BY", "ARRANGE BY", "GROUP BY"],
                    "correct": 1,
                    "explanation": "ORDER BY is used to sort the results in ascending or descending order.",
                    "topic": "SQL",
                    "difficulty": "beginner",
                    "aiGenerated": False
                },
                {
                    "id": f"safe_db_{seed8}_2",
                    "type": "mcq",
                    "section": section,
                    "question": "What does the 'A' in ACID properties stand for in a database?",
                    "options": ["Accessibility", "Availability", "Atomicity", "Algorithms"],
                    "correct": 2,
                    "explanation": "ACID stands for Atomicity, Consistency, Isolation, and Durability.",
                    "topic": "Transactions",
                    "difficulty": "medium",
                    "aiGenerated": False
                }
            ],
            "OS": [
                {
                    "id": f"safe_os_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "What is a deadlock in an operating system?",
                    "options": ["A state where a process is waiting for an I/O device", "A state where two or more processes are waiting for each other to release resources", "A system crash due to memory leak", "A process that terminated unexpectedly"],
                    "correct": 1,
                    "explanation": "Deadlock is a situation where processes are stuck because they are waiting for resources held by each other.",
                    "topic": "Processes",
                    "difficulty": "medium",
                    "aiGenerated": False
                },
                {
                    "id": f"safe_os_{seed8}_2",
                    "type": "mcq",
                    "section": section,
                    "question": "Which scheduling algorithm is non-preemptive?",
                    "options": ["Round Robin", "Shortest Job First (SJF)", "Priority Scheduling (Preemptive)", "First Come First Served (FCFS)"],
                    "correct": 3,
                    "explanation": "FCFS always completes the process once it starts, making it non-preemptive.",
                    "topic": "Scheduling",
                    "difficulty": "beginner",
                    "aiGenerated": False
                }
            ],
            "CN": [
                {
                    "id": f"safe_cn_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "Which layer of the OSI model is responsible for IP addressing?",
                    "options": ["Transport Layer", "Data Link Layer", "Network Layer", "Physical Layer"],
                    "correct": 2,
                    "explanation": "The Network Layer (Layer 3) handles IP addressing and routing.",
                    "topic": "OSI Model",
                    "difficulty": "medium",
                    "aiGenerated": False
                }
            ],
            "OOPS": [
                {
                    "id": f"safe_oops_{seed8}_1",
                    "type": "mcq",
                    "section": section,
                    "question": "Which principle of OOPS refers to the ability of a single interface to represent different underlying forms?",
                    "options": ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"],
                    "correct": 2,
                    "explanation": "Polymorphism allows one interface to be used for a general class of actions.",
                    "topic": "Polymorphism",
                    "difficulty": "beginner",
                    "aiGenerated": False
                }
            ],
            "System Design": [
                {
                    "id": f"safe_sd_{seed8}_1",
                    "type": "short_answer",
                    "section": section,
                    "question": "Explain the concept of Horizontal Scaling vs Vertical Scaling in a backend system. When would you choose one over the other?",
                    "expectedAnswer": "Horizontal scaling adds more machines; Vertical scaling adds more power to existing machine. Horizontal is better for fault tolerance and massive scale.",
                    "rubric": {"excellent": "Explains fault tolerance and cost trade-offs", "good": "Defines both terms", "poor": "Incorrect definitions"},
                    "keywords": ["load balancer", "distributed", "RAM", "CPU"],
                    "topic": "Scalability",
                    "difficulty": "medium",
                    "aiGenerated": False
                }
            ]
        }
        
        # Find matching category or default to CS Fundamentals
        sl = section.lower()
        cat = "CS Fundamentals"
        if "aptitude" in sl or "reasoning" in sl:
            cat = "Aptitude"
        elif any(x in sl for x in ["dsa", "data structure", "algorithm", "coding"]):
            cat = "DSA"
        elif "dbms" in sl or "database" in sl:
            cat = "DBMS"
        elif "os" == sl or "operating system" in sl:
            cat = "OS"
        elif "cn" == sl or "network" in sl:
            cat = "CN"
        elif any(x in sl for x in ["oops", "object oriented", "design pattern"]):
            cat = "OOPS"
        elif any(x in sl for x in ["system design", "scalability", "architecture"]):
            cat = "System Design"
            
        pool = safety_net.get(cat, safety_net["CS Fundamentals"])
        # Return at least 1, up to requested count (cycle through pool if count > pool size)
        result = []
        for i in range(count):
            result.append(pool[i % len(pool)])
        return result

    # ──────────────────────────────────────────────────────────────────────────
    # Public API — generate_test
    # ──────────────────────────────────────────────────────────────────────────

    async def generate_test(
        self,
        student_profile: Dict[str, Any],
        test_config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Generate a complete, fully AI-driven test.
        100% unique per student per attempt.
        """
        cfg = test_config or {}
        num_q_raw = cfg.get("questionsPerSection")
        time_per_raw = cfg.get("timePerSection")

        seed = self._unique_seed(student_profile)
        seed8 = self._trunc(seed, 8)

        logger.info(
            f"[QuestionGenerator] Generating test for '{student_profile.get('name')}' | "
            f"seed={seed8} | role={student_profile.get('targetRole')}"
        )

        stream_cat = self._stream_category(student_profile)
        company = (cfg.get("company") or "").lower().strip()
        company_pattern = self.COMPANY_PATTERNS.get(company)

        # Handle separated test modes (Field vs Skills)
        test_mode = (cfg.get("testMode") or "combined").lower()
        
        final_sections = []
        if test_mode == "skills":
            # ONLY use skills selected by the student
            skill_ratings = student_profile.get("skillRatings", {})
            user_skills = student_profile.get("knownTechnologies", [])
            available_skills = set(list(skill_ratings.keys()) + user_skills)
            
            final_sections = list(available_skills)
            if not final_sections:
                logger.warning("No skills provided for skills test, falling back to field mode")
                test_mode = "field"

        if test_mode == "field" or test_mode == "combined":
            initial_sections = ["Aptitude"]
            stream_cores = list(self.STREAM_SECTIONS.get(stream_cat, {}).keys())
            initial_sections.extend([s for s in stream_cores if s != "Aptitude"])
            
            # For 'field', we don't mix skills. For 'combined', we do (legacy behavior).
            if test_mode == "combined":
                skill_ratings = student_profile.get("skillRatings", {})
                high_skills = [k for k, v in skill_ratings.items() if v >= 6]
                initial_sections.extend(high_skills)
            
            seen = set()
            for s in initial_sections:
                if s.lower() not in seen:
                    final_sections.append(s)
                    seen.add(s.lower())
        
        sections = cfg.get("sections") or final_sections
        # Ensure Aptitude is included if not already present
        if test_mode != "skills" and "Aptitude" not in sections and len(sections) > 0:
            sections.insert(0, "Aptitude")

        # Difficulty distribution based on CGPA and ratings if available
        # If CGPA > 8 or high skill ratings, increase Hard/Advanced percent
        dist = {"easy": 0.15, "medium": 0.40, "hard": 0.30, "advanced": 0.15}
        
        num_q = max(3, min(int(num_q_raw) if num_q_raw is not None else 20, 25))
        time_per_section = int(time_per_raw) if time_per_raw is not None else 1200   # 20 min default

        test_sections = []
        for sec_name in sections:
            logger.info(f"  → Generating section: {sec_name}")
            try:
                qs = await self._generate_section(
                    section=sec_name,
                    profile=student_profile,
                    num_q=num_q,
                    dist=dist,
                    seed=seed,
                    stream_cat=stream_cat,
                    company_pattern=company_pattern,
                    company=company,
                    category=cfg.get("category", "")
                )
                if qs:
                    test_sections.append({
                        "id":        f"sec_{sec_name.lower().replace(' ', '_')}_{self._trunc(seed, 6)}",
                        "name":      sec_name,
                        "questions": qs,
                        "timeLimit": time_per_section,
                    })
                else:
                    logger.warning(f"Section {sec_name} generated with no questions.")
            except Exception as e:
                logger.error(f"Failed to generate section {sec_name}: {e}")
                continue

        total_questions: int = sum(len(s["questions"]) for s in test_sections)  # pyre-ignore[6]
        if total_questions == 0:
            raise ValueError("AI generation failed to produce any valid questions. Please try again or switch model.")
        
        sec_count: int = len(test_sections)
        tt_raw = cfg.get("totalTime")
        total_time: int = int(tt_raw) if tt_raw is not None else (sec_count * time_per_section)

        result = {
            "testId":          f"test_{seed}",
            "studentId":       student_profile.get("id", "unknown"),
            "studentName":     student_profile.get("name", "Student"),
            "targetRole":      student_profile.get("targetRole", "Software Engineer"),
            "field":           student_profile.get("fieldOfStudy", "Generic"),
            "degree":          student_profile.get("degree", "B.Tech"),
            "generatedAt":     datetime.utcnow().isoformat(),
            "company":         company.upper() if company else "TOP-TIER MIX",
            "sections":        test_sections,
            "totalQuestions":  total_questions,
            "totalTime":       total_time,
            "adaptiveDifficulty": True,
            "uniqueToStudent": True,
            "aiGenerated":     True,
        }

        logger.info(
            f"[QuestionGenerator] ✅ Test generated: {total_questions} questions "
            f"across {sec_count} sections (seed={seed8})"
        )
        return result

    # ──────────────────────────────────────────────────────────────────────────
    # Public API — adaptive difficulty
    # ──────────────────────────────────────────────────────────────────────────

    async def adjust_difficulty(
        self,
        performance: Dict[str, Any],
        current_difficulty: str,
    ) -> str:
        levels = self.DIFFICULTY_ORDER
        idx = levels.index(current_difficulty) if current_difficulty in levels else 1

        correct = performance.get("correctAnswers", 0)
        total = max(performance.get("totalAnswers", 1), 1)
        accuracy = correct / total
        streak_correct = performance.get("consecutiveCorrect", 0)
        streak_wrong = performance.get("consecutiveWrong", 0)

        if streak_correct >= 3 and accuracy >= 0.75:
            idx = min(idx + 1, len(levels) - 1)
        elif streak_wrong >= 2 or accuracy < 0.35:
            idx = max(idx - 1, 0)

        return levels[idx]

    # ──────────────────────────────────────────────────────────────────────────
    # Public API — next adaptive question
    # ──────────────────────────────────────────────────────────────────────────

    async def get_next_question(
        self,
        student_profile: Dict[str, Any],
        section: str,
        performance: Dict[str, Any],
        answered_ids: List[str],
    ) -> Dict[str, Any]:
        difficulty = await self.adjust_difficulty(performance, performance.get("currentDifficulty", "medium"))
        stream_cat = self._stream_category(student_profile)
        profile = student_profile or {}
        topics = self._pick_topics(stream_cat, section, profile)
        seed = self._unique_seed(student_profile)
        idx = len(answered_ids)
        topic = topics[idx % len(topics)]
        qtype = self._question_type(section, difficulty, idx)
        profile_ctx = self._profile_context(student_profile)

        if qtype == "coding":
            return await self._gen_coding(section, topic, difficulty, profile_ctx, "", seed, idx)
        elif qtype == "short_answer":
            return await self._gen_short_answer(section, topic, difficulty, profile_ctx, "", seed, idx)
        else:
            return await self._gen_mcq(section, topic, difficulty, profile_ctx, "", seed, idx)

    def _trunc(self, text: str, length: int) -> str:
        """Truncate string and remove special chars."""
        clean = "".join(e for e in str(text) if e.isalnum())
        return clean[:length]

    def _unique_seed(self, profile: Dict[str, Any]) -> str:
        """Generate a stable but unique seed for the student/attempt."""
        uid = str(profile.get("id") or profile.get("userId") or "anon")
        now = datetime.utcnow().strftime("%Y%m%d%H") # Hourly stable seed
        raw = f"{uid}-{now}-{random.random()}"
        return hashlib.md5(raw.encode()).hexdigest()

    # ──────────────────────────────────────────────────────────────────────────
    # Stage 1: Field-based Assessment (60 questions)
    # ──────────────────────────────────────────────────────────────────────────

    async def generate_field_assessment(self, student_profile: Dict[str, Any], test_config: Dict[str, Any] = {}) -> Dict[str, Any]:
        """
        Generate a Stage 1 Field Assessment.
        Total questions: 60.
        Covers core topics of the field from Easy to Hard.
        Focuses on interview and placement readiness.
        """
        stream_cat = self._stream_category(student_profile)
        
        # Get sections for this stream
        sections_dict = self.STREAM_SECTIONS.get(stream_cat, self.STREAM_SECTIONS["computer_science"])
        
        # Core Operational Modules for this Field
        num_sections = len(sections_dict)
        q_per_section = 20  # Full 20 questions per module to ensure comprehensive assessment
        
        # Ensure at least 60 questions for field mastery
        total_target = max(60, num_sections * q_per_section)


        
        seed = self._unique_seed(student_profile)
        
        # Difficulty bias for Stage 1: balanced Easy/Medium/Hard
        dist = {"easy": 0.25, "medium": 0.50, "hard": 0.20, "advanced": 0.05}
        
        tasks = []
        all_sections_data = []
        for section in sections_dict.keys():
            try:
                # Generate section data
                section_data = await self._generate_section(
                    section=section,
                    profile=student_profile,
                    num_q=q_per_section,
                    dist=dist,
                    seed=seed,
                    stream_cat=stream_cat,
                    category='foundational'
                )
                all_sections_data.append(section_data)
            except Exception as e:
                logger.error(f"Critical failure in section generation for {section}: {e}")
                # Inject a whole section of safety questions if the AI engine crashed
                safety_qs = self._get_safety_questions(section, 5, seed)
                all_sections_data.append(safety_qs)
            
            # Small delay between sections to prevent the LLM queue from exploding on Render
            await asyncio.sleep(0.3)
        
        final_sections = []
        total_q = 0
        for i, section_name in enumerate(sections_dict.keys()):
            qs = all_sections_data[i]
            
            # Double-check: If a whole section failed or is empty, inject safety questions
            if not qs or len(qs) == 0:
                logger.error(f"Section generation produced no questions for {section_name}. Filling with safety net.")
                qs = self._get_safety_questions(section_name, 5, seed)
            
            final_sections.append({
                "sectionId": f"sec_{i}",
                "name": section_name,
                "questions": qs,
                "totalQuestions": len(qs)
            })
            total_q += len(qs)
            
        return {
            "testId": f"field_{seed[:8]}",
            "title": f"Stage 1 Core Assessment",
            "description": "Comprehensive field-based assessment covering core concepts and placement topics.",
            "totalQuestions": total_q,
            "sections": final_sections,
            "metadata": {
                "stage": 1,
                "field": stream_cat,
                "generatedAt": datetime.utcnow().isoformat()
            }
        }

    # ──────────────────────────────────────────────────────────────────────────
    # Stage 2: Skill-based Assessment (10 questions per skill)
    # ──────────────────────────────────────────────────────────────────────────

    async def generate_skill_assessment(self, student_profile: Dict[str, Any], skills: List[str], test_config: Dict[str, Any] = {}) -> Dict[str, Any]:
        """
        Generate a Stage 2 Skill-based Assessment.
        Total questions: 10 per skill.
        Purely AI generated from selected student skills.
        """
        seed = self._unique_seed(student_profile)
        stream_cat = self._stream_category(student_profile)
        
        # Adaptive difficulty for Stage 2 - starts medium/hard
        dist = {"easy": 0.10, "medium": 0.40, "hard": 0.40, "advanced": 0.10}
        
        all_skill_data = []
        for skill in skills:
            try:
                skill_data = await self._generate_section(
                    section=skill,
                    profile=student_profile,
                    num_q=10, # Exactly 10 questions per skill as requested
                    dist=dist,
                    seed=seed,
                    stream_cat=stream_cat,
                    category='practical'
                )
                all_skill_data.append(skill_data)
            except Exception as e:
                logger.error(f"Skill section generation failed for {skill}: {e}")
                safety_qs = self._get_safety_questions(skill, 2, seed)
                all_skill_data.append(safety_qs)
            
            await asyncio.sleep(0.3)
        
        final_sections = []
        total_q = 0
        for i, skill_name in enumerate(skills):
            qs = all_skill_data[i]
            final_sections.append({
                "sectionId": f"skill_{i}",
                "name": skill_name,
                "skillName": skill_name,
                "questions": qs,
                "totalQuestions": len(qs)
            })
            total_q += len(qs)
            
        return {
            "testId": f"skill_{seed[:8]}",
            "title": "Stage 2: Advanced Skill Assessment",
            "description": f"Targeted assessment for your selected skills: {', '.join(skills)}",
            "totalQuestions": total_q,
            "sections": final_sections,
            "metadata": {
                "stage": 2,
                "skills": skills,
                "generatedAt": datetime.utcnow().isoformat()
            }
        }

# ──────────────────────────────────────────────────────────────────────────────
# Singleton
# ──────────────────────────────────────────────────────────────────────────────

_instance: Optional[QuestionGenerator] = None


def get_question_generator() -> QuestionGenerator:
    global _instance
    if _instance is None:
        _instance = QuestionGenerator()
    return _instance
